### ISSUE TITLE
Some UI improvements needed for sponsor page 

### ISSUE THREAD

**Issue by Maadhav** [Code-Decoders/safe-team#31]
1. Only the table should be scrollable and not the whole page. 
<img width="1440" alt="Screenshot 2023-05-20 at 8 30 32 AM" src="https://github.com/Code-Decoders/safe-team/assets/21285859/52d7ce81-df7d-4363-92ee-f645d7cb9409">

2. The Circle logo has the text color in white, and since the background of the model is white, switch the image to the dark version, which I had sent as well.
<img width="532" alt="Screenshot 2023-05-20 at 8 31 13 AM" src="https://github.com/Code-Decoders/safe-team/assets/21285859/a4f1bc7a-0f68-4839-bd64-9a19a2446de9">

3. Right now the amount value needs decimals to be accounted for as well, instead could you use ethers utils to convert the user input into 6 decimal number before sending it to the blockchain?
Example: `ethers.utils.parseUnits("1.0", 18);`

**Comment by aooamaster** [comment]
done
